global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'kinetra-rl'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          instance: 'rl-trainer'
